name: deploy

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo /etc/init.d/docker start

      - name: build and test
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build and test
        env:
          PROD_ENV: ${{ secrets.ENV_PROD }}
          DEV_ENV: ${{ secrets.ENV_DEV }}
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "$PROD_ENV" > src/main/resources/application.yml
          else
            echo "$DEV_ENV" > src/main/resources/application.yml
          fi
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-8)
          docker build . -t reservation:$SHORT_SHA -f Dockerfile
#          ./gradlew build -x test
#          RUNNER_TRACKING_ID="" && ls build/libs/*SNAPSHOT.jar | xargs -I{} java -jar {} --spring.profiles.active=prod &
