name: deploy

on:
  push:
    branches:
      - main
      - develop
      - feature/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        uses: actions/setup-java@v3
        with:
          java-version: '11'
        run: |
          ./gradlew build
#          RUNNER_TRACKING_ID="" && ls build/libs/*SNAPSHOT.jar | xargs -I{} java -jar {} --spring.profiles.active=prod &
