name: deploy

on:
  push:
    branches:
      - main
      - develop
      - feature/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build and test
        env:
          ENV: ${{ secrets.ENV_PROD }}
        run: |
          mkdir src/main/resources
          echo "$ENV" > src/main/resources/application.yml
          export SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-8)
          docker build . -t reservation:$SHORT_SHA -f Dockerfile
#          ./gradlew build -x test
#          RUNNER_TRACKING_ID="" && ls build/libs/*SNAPSHOT.jar | xargs -I{} java -jar {} --spring.profiles.active=prod &
