name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build and test
        env:
          PROD_ENV: ${{ secrets.ENV_PROD }}
          DEV_ENV: ${{ secrets.ENV_DEV }}
          DOCKER_HOST: tcp://localhost:2375
        run: |
          if [[ $GITHUB_REF_NAME == 'main' ]]; then
            echo "$PROD_ENV" > src/main/resources/application.yml
          else
            echo "$DEV_ENV" > src/main/resources/application.yml
          fi
          ./gradlew build
#          RUNNER_TRACKING_ID="" && ls build/libs/*SNAPSHOT.jar | xargs -I{} java -jar {} --spring.profiles.active=prod &
